Starting Garak job...
Running Garak scan with command: python3 -m garak --model_type huggingface --model_name gpt2 --probes dan.Ablation_Dan_11_0,dan.AntiDAN,dan.DAN_Jailbreak,dan.Dan_10_0,dan.Dan_11_0,dan.Dan_6_0,dan.Dan_6_2,dan.Dan_7_0,dan.Dan_8_0,dan.Dan_9_0,dan.DUDE,dan.STAN,dan.DanInTheWild,dan.DanInTheWildFull,dan.AutoDAN,dan.AutoDANCached,dan.ChatGPT_Image_Markdown,dan.ChatGPT_Developer_Mode_RANTI,dan.ChatGPT_Developer_Mode_v2 --report_prefix /Users/divyachitimalla/garak/dashboard/reports/a858c976-39ac-4d17-b91e-172aff6d4f08
garak LLM vulnerability scanner v0.12.0.pre1 ( https://github.com/NVIDIA/garak ) at 2025-07-30T09:30:51.322241
ðŸ“œ logging to /Users/divyachitimalla/.local/share/garak/garak.log
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/divyachitimalla/garak/garak/_plugins.py", line 155, in _build_plugin_cache
    for plugin in self._enumerate_plugin_klasses(plugin_type):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/divyachitimalla/garak/garak/_plugins.py", line 188, in _enumerate_plugin_klasses
    mod = importlib.import_module(f"garak.{category}.{module_name}")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.11/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/divyachitimalla/garak/garak/generators/gemini.py", line 10, in <module>
    import google.generativeai as genai
ModuleNotFoundError: No module named 'google.generativeai'
Garak scan completed with exit code: 1
No reports generated
